phoenix-project/phoenix_final/web/router.ex
defmodule PhoenixFinal.Router do
  use PhoenixFinal.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
  end





  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PhoenixFinal.Auth, repo: PhoenixFinal.Repo
  end
  scope "/", PhoenixFinal do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController

  end
  # Other scopes may use custom stacks.
  # scope "/api", PhoenixFinal do
  #   pipe_through :api
  # end
end

phoenix-project/phoenix_final/lib/phoenix_final/endpoint.ex
defmodule PhoenixFinal.Endpoint do
  use Phoenix.Endpoint, otp_app: :phoenix_final

  socket "/socket", PhoenixFinal.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :phoenix_final, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_phoenix_final_key",
    signing_salt: "9nxyLYvt"

  plug PhoenixFinal.Router
end

phoenix-project/phoenix_final/lib/phoenix_final/repo.ex
defmodule PhoenixFinal.Repo do
  use Ecto.Repo, otp_app: :phoenix_final
end

phoenix-project/phoenix_final/web/models/post.ex
defmodule PhoenixFinal.Post do
  use PhoenixFinal.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

phoenix-project/phoenix_final/web/models/user.ex
defmodule PhoenixFinal.User do
  use PhoenixFinal.Web, :model

  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    timestamps()
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, ~w(name username), [])
    |> validate_length(:username, min: 1, max: 20)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, ~w(password), [])
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

phoenix-project/phoenix_final/web/controllers/page_controller.ex
defmodule PhoenixFinal.PageController do
  use PhoenixFinal.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

phoenix-project/phoenix_final/web/controllers/post_controller.ex
defmodule PhoenixFinal.PostController do
  use PhoenixFinal.Web, :controller

  alias PhoenixFinal.Post

  def index(conn, _params) do
    posts = Repo.all(Post)
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    changeset = Post.changeset(%Post{}, post_params)

    case Repo.insert(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: post_path(conn, :index))
  end
end

phoenix-project/phoenix_final/web/controllers/session_controller.ex
defmodule PhoenixFinal.SessionController do
  use PhoenixFinal.Web, :controller
  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
    case PhoenixFinal.Auth.login_by_username_and_pass(conn, user, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> PhoenixFinal.Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end
end

phoenix-project/phoenix_final/web/controllers/user_controller.ex
defmodule PhoenixFinal.UserController do
  use PhoenixFinal.Web, :controller
  alias PhoenixFinal.User

  def index(conn, _params) do
    users = Repo.all(PhoenixFinal.User)
    render conn, "index.html", users: users
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(PhoenixFinal.User, id)
    render conn, "show.html", user: user
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> PhoenixFinal.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
  defp authenticate(conn) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access that page")
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end

end

phoenix-project/phoenix_final/web/views/error_view.ex
defmodule PhoenixFinal.ErrorView do
  use PhoenixFinal.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

phoenix-project/phoenix_final/web/views/layout_view.ex
defmodule PhoenixFinal.LayoutView do
  use PhoenixFinal.Web, :view
end

phoenix-project/phoenix_final/web/views/page_view.ex
defmodule PhoenixFinal.PageView do
  use PhoenixFinal.Web, :view
end

phoenix-project/phoenix_final/web/views/post_view.ex
defmodule PhoenixFinal.PostView do
  use PhoenixFinal.Web, :view
end

phoenix-project/phoenix_final/web/views/session_view.ex
defmodule PhoenixFinal.SessionView do
  use PhoenixFinal.Web, :view
end

phoenix-project/phoenix_final/web/views/user_view.ex
defmodule PhoenixFinal.UserView do
  use PhoenixFinal.Web, :view
  alias PhoenixFinal.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

phoenix-project/phoenix_final/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PhoenixFinal!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ol class="breadcrumb text-right">
          <%= if current_user = assigns[:current_user] do %>
            <li><%= @current_user.username %></li> <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li> <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </div>


      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
      <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

phoenix-project/phoenix_final/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

phoenix-project/phoenix_final/web/templates/post/edit.html.eex
<h2>Edit post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :update, @post) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

phoenix-project/phoenix_final/web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

phoenix-project/phoenix_final/web/templates/post/index.html.eex
<h2>Listing posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for post <- @posts do %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>

        <td class="text-right">
          <span><%= link "Show", to: post_path(@conn, :show, post), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Edit", to: post_path(@conn, :edit, post), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "New post", to: post_path(@conn, :new) %></span>

phoenix-project/phoenix_final/web/templates/post/new.html.eex
<h2>New post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :create) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

phoenix-project/phoenix_final/web/templates/post/show.html.eex
<h2>Show post</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

</ul>

<span><%= link "Edit", to: post_path(@conn, :edit, @post) %></span>
<span><%= link "Back", to: post_path(@conn, :index) %></span>

phoenix-project/phoenix_final/web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Log in", class: "btn btn-primary" %>
<% end %>

phoenix-project/phoenix_final/web/templates/user/index.html.eex
<h1>Listing Users</h1>
<table class="table">
  <%= for user <- @users do %>
    <tr>
      <td><b><%= first_name(user) %></b> (<%= user.id %>)</td>
      <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
    </tr>
  <% end %>
</table>

phoenix-project/phoenix_final/web/templates/user/new.html.eex
<h1> New User </h1>
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :name, placeholder: "Name", class: "form-control" %> <%= error_tag f, :name %>
  <%= text_input f, :username, placeholder: "Username", class: "form-control" %> <%= error_tag f, :username %>
  <%= password_input f, :password, placeholder: "Password", class: "form-control" %> <%= error_tag f, :password %>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

phoenix-project/phoenix_final/web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render "user.html", user: @user %>

phoenix-project/phoenix_final/web/templates/user/user.html.eex
<b><%= first_name(@user) %></b> (<%= @user.id %>)